### PR TITLE
Let TreatTSqlWarningsAsErrors win

### PR DESCRIPTION
**Pull request by AroglDarthu**
Ignore `TreatWarningsAsErrors` if `TreatTSqlWarningsAsErrors` has been set. See #185

### CODE REVIEW

**Review by jmezach — APPROVED** [review]
LGTM

**Comment by jmezach** [comment]
@jeffrosenberg @ErikEJ Could either of you have a look at this one as well? Thanks!

**Review by jeffrosenberg — APPROVED** [review]
LGTM

**Comment by jmezach** [comment]
@AroglDarthu Thank you for your contribution!

**Pull request merged**
