### PR TITLE
AssemblyName is now TargetName

### PR DESCRIPTION
**Pull request by brettrowberry**
I'm not sure if this line should be edited or removed.

The problem was introduced by me in #66

### CODE REVIEW

**Review by jmezach — APPROVED** [review]
LGTM. I think we want to push people to use `<TargetName>` as the preferred method although `<AssemblyName>` will also work. I just feel `<TargetName>` makes more sense in this case.

**Comment by brettrowberry** [comment]
I didn’t test. In 1.8.1 AssemblyName made publish fail. Does it work in 1.9.0?

**Comment by jmezach** [comment]
Yes, with 1.9.0 publish works with both `<TargetName>` and `<AssemblyName>` as expected.

**Review by jeffrosenberg — APPROVED** [review]

**Comment by jmezach** [comment]
@brettrowberry Thanks for your contribution.

**Pull request merged**
