### PR TITLE
Attempt to fix issue with extra command line arguments

### LINKED ISSUE #500: Unrecognized command or argument '-p:UseSharedCompilation=false' when running on Github build
Version : 2.6.1
I'm receiving this strange error when running on Github Actions runner on a new workflow. Strangely the same build works on an older workflow (with exact same parameters). The only difference is the slightly updated `ubuntu-latest` image the runner is using for one workflow but not the other. The error:
```
/home/runner/.nuget/packages/msbuild.sdk.sqlproj/2.6.1/Sdk/Sdk.targets(242,5): error MSB3073: The command "dotnet "/home/runner/.nuget/packages/msbuild.sdk.sqlproj/2.6.1/Sdk/../tools/net8.0/DacpacTool.dll" build -o "obj/Debug/*****Build.dacpac" -n "*****.Build" -v "1.0.0" -sv Sql140 -i "obj/Debug/***.InputFiles.txt"   -bp AllowSnapshotIsolation=True -dp IncludeCompositeObjects=true --predeploy ../*****/Script.PreDeployment.sql --postdeploy ../*****/Script.PostDeployment.sql --refactorlog ../*****/*****i.refactorlog      " exited with code 1. [/home/runner/work/*****/DB/Build/*****.Build.csproj]
  Using target framework net8.0 to run DacpacTool
  Unrecognized command or argument '-p:UseSharedCompilation=false'.
  Unrecognized command or argument '-p:EmitCompilerGeneratedFiles=true'.
```

For the life of me I can't figure out why this is happening. Any suggestions are welcome. Thank you.

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #500

### CODE REVIEW

**Comment by jmezach** [comment]
Can we test that this actually fixes something?

**Comment by ErikEJ** [comment]
If we build a preview package that the OP can consume in his pipeline?

**Comment by jmezach** [comment]
Sure. I can upload the preview package to NuGet.org tomorrow.

**Comment by jmezach** [comment]
Turned out to be really busy last Friday so I didn't get around to it. But I've uploaded a pre-release version of this PR to NuGet.org which should be available soon. Version 2.7.0-beta.30.g42c33ba1c7.

**Comment by ErikEJ** [comment]
@popcatalin81 Are you able to test this preview package in your pipeline?

https://www.nuget.org/packages/MSBuild.Sdk.SqlProj/2.7.0-beta.30.gf2c33ba1c7

**Comment by ErikEJ** [comment]
@popcatalin81 Ping?

**Comment by popcatalin81** [comment]
> @popcatalin81 Ping?

Yes, I will test right away. I was ooo for the past week.

**Comment by popcatalin81** [comment]
@ErikEJ This took longer than I wanted it too due to some big changes to the project pipeline that made the whole CI be offline for the past weeks.

However I can confirm now the fix worked.

**Review by jeffrosenberg — APPROVED** [review]

**Review by jmezach — APPROVED** [review]

**Pull request merged**
