### PR TITLE
Support .NET 7.0 RTM

### LINKED ISSUE #353: VS 2022 v.17.4.0 causes "The current SDK bundles target framework '7.0' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 3.1, 5.0 or 6.0"
Hi, I recently updated Visual Studio 2022 from 17.3.6 version to 17.4.0 version.
After the update, I started to receive this build error locally on a MSBuild.Sdk.SqlProj project, version 2.0.0:

**The current SDK bundles target framework '7.0' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 3.1, 5.0 or 6.0, or file an issue at https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/ to add support. If you have preview SDKs installed, you may have to use a global.json file: https://docs.microsoft.com/dotnet/core/tools/global-json _**

I've also noticed that my installed SDKs have changed: after VS update they are
`C:\Users\XXXXXX>dotnet --list-sdks`
`2.1.524 [C:\Program Files\dotnet\sdk]`
`3.1.422 [C:\Program Files\dotnet\sdk]`
`7.0.100 [C:\Program Files\dotnet\sdk]`

Previously (1 month ago, when I was able to build the project on my VS 2022) they were
`C:\Users\XXXXXX>dotnet --list-sdks`
`2.1.524 [C:\Program Files\dotnet\sdk]`
`3.1.422 [C:\Program Files\dotnet\sdk]`
`6.0.402 [C:\Program Files\dotnet\sdk]`

I rollbacked VS update (returning to 17.3.6 version) and I observed that:
1. The SDK was rollbacked too from 7.0.100 to 6.0.402
2. My MSBuild.Sdk.SqlProj now builds again.

I think a new version of MSBuild.Sdk.SqlProj is necessary to support VS 2022 v.17.4.0 and newer versions of Microsoft IDE.

### PR DESCRIPTION
**Pull request by ErikEJ**
@jmezach @jeffrosenberg  I do not understand versioning - where do I set it? Or it it set by magic 🧙 ? 

fixes #353

### CODE REVIEW

**Comment by ErikEJ** [comment]
Also, how do I get the sqltools module down locally?

**Comment by jmezach** [comment]
@ErikEJ We're using https://github.com/dotnet/Nerdbank.GitVersioning for versioning. Basically we can merge a set of changes to master and then when we're ready to release we run the `nbgv prepare-release` command which will create a release branch for that release and then bumps the version number on master.

sqltools is a submodule, so you should be able to get that by running:

```
git submodule init
git submodule update
```

**Comment by ErikEJ** [comment]
This test step failing:

 # Build the project using exact version number
    - name: build project (exact version / MSBuild resolution)
      run: dotnet build ./test/TestProjectWithSDKRef/TestProjectWithSDKRef.csproj /bl /p:DependencyVersion="$Env:NBGV_NuGetPackageVersion" /warnaserror:SQL71502
      shell: pwsh

I have no clue where it gets the 5.0 version number from?

**Comment by jmezach** [comment]
It looks like the macOS and Windows runners have the .NET 5 SDK installed by default or something? We are installing the 3.1 version, but of course 5.0 is newer so it will pick that. Kinda weird though that those runners still have an unsupported version installed?

**Review by jmezach — APPROVED** [review]

**Comment by ErikEJ** [comment]
@jmezach I also updated the Ubuntu runner, as 18.04 was deprecated

**Comment by ErikEJ** [comment]
@jeffrosenberg Could you have a look at this?

**Comment by ErikEJ** [comment]
@jmezach Hmm.. any clues tom why deploy.sqlpackage failed?

**Comment by ErikEJ** [comment]
@jmezach  I was not using 20.04 everywhere!

**Review by jeffrosenberg — APPROVED** [review]
LGTM!

@ErikEJ - just curious why the Ubuntu version change needed to be reverted, was something not working?

**Comment by jmezach** [comment]
@jeffrosenberg Looks like SqlPackage doesn't work on that Ubuntu version: https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/actions/runs/3436079040/jobs/5729274646#step:5:8.

I guess it's fine for now and not something we can fix anyway. So I'll go ahead and merge this and release a new version so that folks can start using this with .NET 7.

**Comment by ErikEJ** [comment]
@jeffrosenberg Yes, I think something extra needs to be done (or maybe use 22.04) - but it seems out of scope for this change

**Pull request merged**
