### PR TITLE
SqlCmdVariable DefaultValue should not be written to .dacpac as per docs

### LINKED ISSUE #448: Defining SQLCMD variables in the project prevents them from being set via environment variables
It seems to me that defining the `<SqlCmdVariable> ... </SqlCmdVariable>` is actually worse than not defining it.

I am building a .dacpac with this SDK with a Post-Deploy script that uses variables like this:
```sql
IF (1 = ISNULL($(SQLCMD_DEPLOY_CONFIGS), 0))
BEGIN
# ...
END
```
I am **not** defining  `<SqlCmdVariable> ... </SqlCmdVariable>` anywhere.
1. Running `sqlpackage.exe /a:Publish ...` in a container where the SQLCMD_DEPLOY_CONFIGS environment variable is defined results in the value from the environment variable being replaced in the script.
2. Running `sqlpackage.exe /a:Publish ... /v:SQLCMD_DEPLOY_CONFIGS=0` also works, although it prints _"The following SqlCmd variables are not defined in the target scripts: SQLCMD_DEPLOY_CONFIGS."_

**BUT**

If I go and now define:
```xml
<SqlCmdVariable Include="SQLCMD_DEPLOY_CONFIGS">
		<!--Defines whether configuration scripts should be deployed: 0 - No, 1 - Yes-->
	<DefaultValue>$(SQLCMD_DEPLOY_CONFIGS)</DefaultValue>
	<Value>$(SQLCMD_DEPLOY_CONFIGS)</Value>
</SqlCmdVariable>
```

then the approach with the environment variable (1) **no longer works**. So to me it seems that it is worse to define the sqlcmd vars?

### PR DESCRIPTION
**Pull request by ErikEJ**
https://learn.microsoft.com/sql/tools/sql-database-projects/concepts/sqlcmd-variables

fixes #448

### CODE REVIEW

**Comment by ErikEJ** [comment]
@jmezach Any idea why the build failed?

**Comment by jmezach** [comment]
Yeah, it looks like we're being hit again by having a submodule dependency ;).

**Review by jmezach — APPROVED** [review]
LGTM. One thing I'm wondering whether we now need to pass the values of SqlCmd variables to the DacpacTool from the SDK at all since we're not doing anything with it anyway?

**Comment by ErikEJ** [comment]
Correct, but this change just avoids any SDK changes

**Comment by ErikEJ** [comment]
Maybe the docs need adjusted as well, I will check

**Comment by ErikEJ** [comment]
@jmezach Updated the readme

**Review by jeffrosenberg — APPROVED** [review]

**Pull request merged**
