### PR TITLE
Add GenerateScript

### PR DESCRIPTION
**Pull request by bheemvennapureddy**
Update existing test where we refer other dacpacs like master dacpac here to  GenerateScript

refers https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/591

### CODE REVIEW

**Review by jeffrosenberg — CHANGES_REQUESTED** [review]
I'm not clear on the purpose of this PR. Instead of a commit message saying _what_ you changed, please expand to explain _why_, including the number of the issue this PR resolves.

**Comment by bheemvennapureddy** [comment]
@jeffrosenberg updated the description if that helps - my intention was to test whether the generate script with external dacpac reference as the issue referred was failing with that use case

**Comment by ErikEJ** [comment]
@bheemvennapureddy Did you run the test project and what was the outcome?

**Comment by ErikEJ** [comment]
I did a replacement PR, works fine on my PC 😄

**Pull request closed without merging**
