### PR TITLE
Attempt to fix #615

### LINKED ISSUE #615: Version 2.8.1 - master.dacpac reference is not found
Version: 2.8.1
Deployment on Docker image mcr.microsoft.com/mssql/server:2019-latest
Sqlpackage version tested with 150.* and the latest 162.3.566.1

sqlpackage returns error:

```
Initializing deployment (Start) 2024-08-30 12:41:29 *** No file was supplied for reference master.dacpac; deployment might fail. When package was created, the original referenced file was located C:\Users\username\.nuget\packages\microsoft.sqlserver.dacpacs.master\150.1.1/tools/master.dacpac. 2024-08-30 12:41:29 Initializing deployment (Failed)
```

Notes:
* master.dacpac is in the same directory as dacpac of database I want to deploy;
* master is referenced:
```xml
<Project Sdk="MSBuild.Sdk.SqlProj/2.8.1">
     ...
    <ItemGroup>
        <PackageReference Include="Microsoft.SqlServer.Dacpacs.Master" DacpacName="master" DatabaseVariableLiteralValue="master" Version="150.1.1" />
    </ItemGroup>
</Project>
```
* issue gone once ```<Project Sdk="MSBuild.Sdk.SqlProj/2.8.1">``` was changed to ```<Project Sdk="MSBuild.Sdk.SqlProj/2.7.2">```

### PR DESCRIPTION
**Pull request by ErikEJ**

### CODE REVIEW

**Comment by jmezach** [comment]
This looks good in theory. I guess we need to test it to make sure it actually solves #615 ;).

**Comment by ErikEJ** [comment]
@jmezach Agree, I have no idea - could we publish a preview?

**Comment by ErikEJ** [comment]
@jmezach Unable to merge due to two required approvers with write access to the repo...

**Comment by jmezach** [comment]
I'll do a forced merge for this one and then cherry-pick it to our release branch and publish a patch release.

**Pull request merged**
