### PR TITLE
Remove support for netcoreapp2.1 and add support for net6.0

### PR DESCRIPTION
**Pull request by AroglDarthu**
Solves #192 and adds support for net6.0

### CODE REVIEW

**Comment by AroglDarthu** [comment]
Help wanted with following problem: https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/192#issuecomment-921158637

**Comment by AroglDarthu** [comment]
@jmezach The build pipeline does not yet support `net6.0 sdk`

**Comment by jmezach** [comment]
@AroglDarthu We can fix the pipeline by modifying [the workflow](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/master/.github/workflows/main.yml). We should probably remove .NET Core 2.1 there as well and add .NET 6. Be aware that there are a couple of places where we install .NET SDK's in there.

Really appreciate you helping us out with this!

**Comment by AroglDarthu** [comment]
Cool. Never looked at github workflows before. I'll do some reading on it in the weekend ;-)

**Comment by jmezach** [comment]
Looks like this is finally working, so I think it will be a good idea to merge to master and ship a preview release for folks that are on .NET 6 already while we wait for a stable version of DACFX before we ship a stable version. @ErikEJ @jeffrosenberg Perhaps you guys can give this a review. Thanks to @AroglDarthu for his initial work on this.

**Review by ErikEJ — APPROVED** [review]

**Review by jeffrosenberg — APPROVED** [review]
LGTM

**Pull request merged**
