### PR TITLE
Update to latest DacFX

### PR DESCRIPTION
**Pull request by ErikEJ**

### CODE REVIEW

**Comment by jmezach** [comment]
Any release notes we need to be aware of?

**Comment by ErikEJ** [comment]
@jmezach A list of fixed bugs are [here](https://github.com/microsoft/DacFx/milestone/8?closed=1)

**Comment by ErikEJ** [comment]
@jmezach Wonder if it is time to use a newer macos runner, macos 11 is deprecated...

**Comment by jmezach** [comment]
I guess. Should be fairly easy by just modifying the workflow.

**Comment by ErikEJ** [comment]
I can try and see how it goes

**Comment by ErikEJ** [comment]
@jmezach CI unblocked

**Review by jmezach — APPROVED** [review]
LGTM

**Review by jeffrosenberg — APPROVED** [review]

**Pull request merged**
